quarkus :
  datasource :
    password : 1234567
    username : tinnova
    jdbc :
      max-size : 16
      url : jdbc:h2:mem:vehicle
  hibernate-orm :
    log :
      sql : true
    database :
      generation : update
  http :
    static-extensions : html,js,json,css
    cors :
      ~ : true
      origins : '*'
      headers : '*'
      methods : '*'

